#!/usr/bin/env zsh
# -*- mode: sh; sh-indentation: 4; indent-tabs-mode: nil; sh-basic-offset: 4;-*-
# Copyright (c) 2023 Sebastian Gniazdowski
#
libexec/clone() {
    # Preamble – emulate & 0=…
    0=${${ZERO:-${(%):-%x}}:A}
    source $0:h:h/share/preamble.inc.zsh

    local -a opts; local -A Opts
    zi÷parse-opts "C: -dir:" Opts opts "$@"||return 7
    set -- "$reply[@]"
    zi÷opt-cascade Opts -C --dir
    zi÷reset

    local -a qcmd=(command git -C ${Opts[-C]:=$PWD} clone --progress "$1" $2)
    zi÷run-command -C ${Opts[-C]} -- "$qcmd[@]" |& zi÷git-proc-out

    return $?
}
# vim:ft=zsh:sw=4:sts=4:et
