#!/usr/bin/env zsh

libexec/console(){
    0=${${ZERO:-${(%):-%x}}:A}
    source $0:h:h/share/preamble.inc.zsh --fun

    local -A Opts; local -a opts
    int/iq::parse-opts "C: -dir: s -sort R -reverse" Opts opts "$@"||\
        {iqerr incorrect options given to {cmd}${${@:#-*}[1]}{%}; return 7;}
    set -- "$reply[@]"

    [[ -x $ZIQDIR/smart-consoles/iq$1 ]]&&\
        $ZIQDIR/smart-consoles/iq$1 $opts -- "${(@)@[2,-1]}"
}
