#!/usr/bin/env zsh
# -*- mode: sh; sh-indentation: 4; indent-tabs-mode: nil; sh-basic-offset: 4;-*-
# Copyright (c) 2023 Sebastian Gniazdowski
#
libexec/fetch() {
    0=${${ZERO:-${(%):-%x}}:A}
    source $0:h:h/share/preamble.inc.zsh

    local -a opts; local -A Opts
    int/iq::parse-opts "C: -dir: p -progress q -quiet" Opts opts "$@"||\
        {iqerr incorrect options given to {cmd}fetch{%}; return 7}
    set -- "$reply[@]"
    int/iq::opt-cascade Opts -C --dir -p --progress -q --quiet
    int/iq::reset

    int/iq::get-file "$opts[@]" -- "$@"

    return $?
}
# vim:ft=zsh:sw=4:sts=4:et
